spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-google-id
            client-secret: dummy-google-secret
          github:
            client-id: dummy-github-id
            client-secret: dummy-github-secret
